### ISSUE TITLE
GitHub Action checks failing due to missing API key

### ISSUE THREAD

**Issue by sebpardo** [ropensci/rebird#100]
GitHub Actions checks are failing as they require an eBird API key to properly run the tests. I'm unsure of how to securely store an API key for those checks without making it public.

**Comment by slager** [comment]
Two GitHub Actions runs seemed to fail for non-rebird reasons.  Maybe try rerunning the failed ones?

https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

**Comment by sebpardo** [comment]
The error is in ubuntu-latest (release) and ubuntu-latest (oldrel-1) and it's an issue when setting up R dependencies with installing the withr package:

```
Error: 
  ! error in pak subprocess
  Caused by error in `verify_extracted_package(filename, pkg_cache)`:
  ! 
  '/tmp/Rtmp6pgtjM/file13bc3a8e8aa6/src/contrib/x86_64-pc-linux-gnu-ubuntu-22.04/4.3/withr_3.0.0.tar.gz'
  is not a valid binary, it is missing withr/Meta/package.rds.
```

For some reason the ubuntu-latest (devel) build extracts withr just fine and passes. I think we can safely ignore these two build fails?

**Comment by slager** [comment]
Yes, I think can be ignored.  Or could try re-running the failed actions (see above comment) and see if that produces a nice green check mark.
