### ISSUE TITLE
Make `ebirdregioncheck()` and `ebirdloc()` defunct

### ISSUE THREAD

**Issue by sebpardo** [ropensci/rebird#112]
`ebirdregioncheck()` has been marked as deprecated for several years now and it should be made defunct in the next version update.

@slager I'm flagging this here so you don't convert the tests for this function to `vcr`.

**Comment by slager** [comment]
@sebpardo What about `ebirdloc`?

**Comment by sebpardo** [comment]
That one as well, good catch, I had forgotten about it!
