### ISSUE TITLE
`ebirdchecklist()` fails when checklists includes two types of media

### ISSUE THREAD

**Issue by sebpardo** [ropensci/rebird#125]
I wanted to use [one of the best checklists ever submitted to eBird](https://ebird.org/checklist/S139153079) as the example for `ebirdchecklist()` in the README and vignette, however the function throws an error:

```r
library(rebird)

ebirdchecklist("S139153079")
#> Error in `$<-.data.frame`(`*tmp*`, "mediaCounts", value = c(NA, NA, NA, : replacement has 198 rows, data has 99
```

The culprit is this line 

https://github.com/ropensci/rebird/blob/f9301b7e3166194880adb12e68e91326a8b2ff24/R/ebirdchecklist.R#L107

which fails when `obs_df$mediaCounts` is a data frame with more than one column:

```r
head(obs_df$mediaCounts)
#>    P  V
#> 1 NA NA
#> 2 NA NA
#> 3 NA NA
#> 4 NA NA
#> 5 NA NA
#> 6 NA NA

tail(obs_df$mediaCounts)
#>     P  V
#> 94  2 NA
#> 95  2 NA
#> 96 NA 10
#> 97  4 NA
#> 98 NA NA
#> 99  1 NA

class(obs_df$mediaCounts)
#> [1] "data.frame"
```

We need to make sure this function works when there are multiple types of media in a given checklist. Perhaps we need to output three separate columns with values for `photoCounts`, `videoCounts`, and `audioCounts` when relevant?

**Comment by slager** [comment]
Taking a look
