### ISSUE TITLE
Addition of GitHub Action to update `rebird::tax` dataset on a schedule?

### ISSUE THREAD

**Issue by jrdnbradford** [ropensci/rebird#131]
The docs state that the internal taxonomy is kept up to date only with each package release. Is there any interest in a GitHub action that updates the taxonomy on a scheduled basis and puts in a PR with the updated dataset so that the development version is always up to date?

If so, let me know and I'd be happy to work on this and put in a PR.

**Comment by slager** [comment]
Thanks for the offer @jrdnbradford. It's actually almost no work for the maintainers to refresh the eBird taxonomy once a year -- the main thing is just remembering to do it.  I think a good balance here could be just be having an action that runs once a week or so and if the taxonomy has been bumped creates an issue reminding to update the taxonomy. @sebpardo what do you think?

**Comment by jrdnbradford** [comment]
@slager I didn't realize the [taxonomy](https://ebird.org/science/use-ebird-data/the-ebird-taxonomy) was only updated on a roughly yearly basis. Also seems like there could potentially be required changes to the [`tax` dataset documentation](https://github.com/ropensci/rebird/blob/master/R/data.R) that wouldn't be easily automatable. Given this I'd agree an issue is a better fit. 🐦 

If there's agreement, I can open a PR with a potential solution for further discussion.

**Comment by sebpardo** [comment]
This is a great idea @jrdnbradford! I think the method you suggest @slager would work well given the inconsistent timing of the annual taxonomy update and any potential changes that need to be done by hand.

Please go ahead with a PR for this.
