### ISSUE TITLE
Is it possible to map the locations of the bird observations?

### ISSUE THREAD

**Issue by CordnyNederkoorn** [ropensci/rebird#37]
Hi,

Is it possible to map (google maps, OpenStreetMap) multiple locations of the bird observations via R rebird or other R package?
For instance the locations (Long. and lat.) of a specific bird in the USA found with ebirdregion function:

Example:
ebirdregion(region = 'US', species = 'Passer domesticus')

Best,
Cordny
the Netherlands

**Comment by sckott** [comment]
hi @CordnyNederkoorn are you looking for interactive maps, static maps (using base R graphics, or ggplot2)?  This package focuses on getting eBird data, but we can help you visualize

**Comment by CordnyNederkoorn** [comment]
The data and Visualization I'm looking for, can you give me some pointers? Thanks!

**Comment by sckott** [comment]
* One option is to search ebird data via `spocc` package https://cran.rstudio.com/web/packages/spocc/ - & https://cran.rstudio.com/web/packages/spoccutils/ has a bunch of functions to help you visualize that data
* If you want to make vizualizations yourself, here's an example making an interactive leaflet map:

```r
library(rebird)
library(leaflet)
res <- ebirdregion(region = 'US', species = 'Passer domesticus')
leaflet(data = res) %>% 
  addTiles() %>% 
  addCircleMarkers()
```

<img width="732" alt="screen shot 2015-09-17 at 12 03 05 pm" src="https://cloud.githubusercontent.com/assets/577668/9943085/156bf908-5d34-11e5-9163-0a9e49b1d1bb.png">


that's an interactive map you can zoom in on, etc, but static here

**Comment by CordnyNederkoorn** [comment]
Thanks, I've tried leaflet already, but only got one marker with data from 1 sighting of Passer domesticus from the ebirdregion-function hardcoded in leaflet:

library(leaflet)
m <- leaflet()
m <- addTiles(m)
m <- addMarkers(m, lng= 3.751218  ,lat=51.98096, popup="Passer domesticus NL")

I'm a newbie to R, so pardon for the code :) , but I'm learning!
leaflet(data = res) would solve the hardcoding problem. 
I'll have a look at the spocc package.


Many thanks!

**Comment by sckott** [comment]
Note that it works just fine specifying data in the addmarkers call too e.g., `addCircleMarkers(data = res)`

**Comment by CordnyNederkoorn** [comment]
yes it does, thanks !
