### ISSUE TITLE
Latest build failing on AppVeyor

### ISSUE THREAD

**Issue by sebpardo** [ropensci/rebird#49]
The last 3 or 4 versions of rebird have all failed on AppVeyor (https://ci.appveyor.com/project/sckott/rebird/build/1.0.480#L371). When checking on `devtools::win_build`, rebird builds successfully. 

Why would it fail while "checking whether package 'rebird' can be installed"?

**Comment by sckott** [comment]
probably related to https://ci.appveyor.com/project/sckott/rebird/build/1.0.480#L35 - trying something will report back in a bit

**Comment by ateucher** [comment]
Also could be related to https://github.com/krlmlr/r-appveyor/issues/70?

**Comment by sebpardo** [comment]
Thank you for the heads up @sckott and @ateucher! Looks like it has nothing to do with rebird, so I'll wait for a fix.

**Comment by sebpardo** [comment]
Build is passing now due to changes on appveyor.
