### ISSUE TITLE
replace httr with crul

### ISSUE THREAD

**Issue by sckott** [ropensci/rebird#50]

**Comment by sebpardo** [comment]
Hi @sckott ,

I was hoping to submit and updated version to CRAN, given that in the current version there `ebirdfreq` fails. I was playing around trying to wrap my head around crul, but I don't think I understand its inner workings well enough to replace httr yet. How critical is relaceing httr with crul for the next CRAN update?

**Comment by sckott** [comment]
not critical - in fact you can stick with `httr` - totally up to you

**Comment by sebpardo** [comment]
I'll stick with `httr` as it is working fine as is, and submit the latest version to CRAN today.
