### ISSUE TITLE
rbind_all() deprecated, replace with bind_rows()

### ISSUE THREAD

**Issue by madelynore** [ropensci/rebird#51]
Hi,

The ebirdregion() function isn't work. This is the error message:

```
Warning message:
`rbind_all()` is deprecated. Please use `bind_rows()` instead. 
```

**Comment by sckott** [comment]
thanks @madelynore that is a warning though not an error - did the function not work or did it work but give that warning?

**Comment by madelynore** [comment]
Oop, just a warning. But another question, how far back can ebirdregion() go?

**Comment by sckott** [comment]
(i should say that warning is fixed in the development version here - so will go away in next version to CRAN)

i think it might only go back 6 months, but not sure @rmaia @sebpardo ?

**Comment by sebpardo** [comment]
Hi @madelynore, the `back` argument in the `ebirdregion` function specifies the number of days back to look for observations, and has a maximum value of 30 (which is the limit set by eBird in their API).

**Comment by sebpardo** [comment]
Hi @madelynore, the `back` argument in the `ebirdregion` function specifies the number of days back to look for observations, and has a maximum value of 30 (which is the limit set by eBird in their API).

**Comment by madelynore** [comment]
Thank you!
