### ISSUE TITLE
As of 2017-04-06, ebirdfreq returns a 404 error

### ISSUE THREAD

**Issue by cmartin** [ropensci/rebird#54]
For example, this piece of code from the examples is not working anymore :
`ebirdfreq(loctype = 'hotspots', loc = 'L196159')`

From looking at the code, it seems the url is constructed with a capitalized version of the url : 
`url <- "http://ebird.org/ebird/BarChart"` which, as of today does not seem to be supported.

For example, compare these : 
[http://ebird.org/ebird/barchart?byr=1900&eyr=2017&bmo=1&emo=12&r=US-AL](http://ebird.org/ebird/barchart?byr=1900&eyr=2017&bmo=1&emo=12&r=US-AL)
[http://ebird.org/ebird/BarChart?byr=1900&eyr=2017&bmo=1&emo=12&r=US-AL](http://ebird.org/ebird/BarChart?byr=1900&eyr=2017&bmo=1&emo=12&r=US-AL)

This happens with version 0.3.0, latest version on CRAN

**Comment by sckott** [comment]
@cmartin i think this was fixed in #52 - but i'll let @sebpardo speak to this

**Comment by cmartin** [comment]
Ah, year, sorry. #52 seems to contain the fix.

**Comment by sebpardo** [comment]
Thanks for reminding me of this @cmartin, I'll submit the newest version to CRAN ASAP!

**Comment by plorch** [comment]
This bug seems to have resurfaced.  I am running R version 4.0.3 on Windows10. rebird version 1.1.0.  This command
`ebirdfreq(loctype = "hotspots",loc = "L618902",startyear = 2014,endyear = 2014,long = F)` 
returns a tibble with html in it, not a dataframe.

```
> ebirdfreq(loctype = "hotspots",loc = "L618902",startyear = 2014,endyear = 2014,long = F)
# A tibble: 912 x 2
   comName `January-1`                                                                      
   <chr>   <chr>                                                                            
 1 ""      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':               
 2 ""      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],        
 3 ""      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=            
 4 ""      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f~
 5 ""      })(window,document,'script','dataLayer','GTM-P7854M');</script>                  
 6 ""      <!-- End Google Tag Manager -->    <meta charset=utf-8>                          
 7 ""      <meta http-equiv=X-UA-Compatible content=IE=edge,chrome=1>                       
 8 ""      <title>Sign in</title>                                                           
 9 ""      <meta charset=utf-8>                                                             
10 ""      <meta http-equiv=x-ua-compatible content=ie=edge>                                
# ... with 902 more rows
```

**Comment by sebpardo** [comment]
Hi @plorch, this problem is actually different from the one discussed previously in this issue, and stems from eBird now requiring users to be logged in to download frequency data (`ebirdfreq()` is the one function on `rebird` that doesn't use eBird's API, thus we can't authenticate each user with the API token for this request anymore). Unfortunately it looks like we can't sort this out ourselves, but I'll contact eBird Central to see whether the frequency data can be requested through their API. See https://github.com/ropensci/rebird/issues/82 for more details on this issue.
