### ISSUE TITLE
Retrieving observations more than 30 days back

### ISSUE THREAD

**Issue by choisy** [ropensci/rebird#59]
Why do the functions make it impossible to retrieve observations more than 30 days back?

**Comment by sebpardo** [comment]
The 30-day limit isn't coded into the `rebird` functions but instead is set by the eBird API server, which I imagine is in place to avoid extremely large database queries from being automated and potentially slowing down/crashing the server.

**Comment by sckott** [comment]
@choisy there is a pkg in ropensci review for bulk ebird data https://github.com/ropensci/onboarding/issues/136
