### ISSUE TITLE
API v2?

### ISSUE THREAD

**Issue by sckott** [ropensci/rebird#63]
@sebpardo looks like they want everyone to move to using the v2 api 

https://documenter.getpostman.com/view/664302/ebird-api-20/2HTbHW

do you have time to work on making the switch?

**Comment by sckott** [comment]
i'm starting to get failures with all ebird queries in the `spocc` package - i think it's time to make the switch

**Comment by sebpardo** [comment]
Hi @sckott,

Unfortunately I have very little spare time during the next few months (postdoc + upcoming conferences + finishing PhD papers), but I could chip in if it's a collective effort. I've already had a good look at the new API and it requires major rewriting of every function in the package, see https://github.com/ropensci/rebird/issues/58#issuecomment-348863133 for more info.

Regarding failures with queries, is that the CRAN version of rebird or the Github one? The one in CRAN doesn't use https, which now redirects to http and unfortunately double encodes it causing problems (see #62). This has been updated in the Github version, and the tests seem to work properly. I was hoping to hold on releasing a new version before the switch, but perhaps it's wise to release a version as-is now to fix this issue quickly, and then have a separate release for the new API?

**Comment by sebpardo** [comment]
Pinging @ateucher & @rmaia

**Comment by rmaia** [comment]
I can chip in a collective effort too

**Comment by sckott** [comment]
@sebpardo 

> perhaps it's wise to release a version as-is now to fix this issue quickly, and then have a separate release for the new API?

sure, makes sense

**Comment by sebpardo** [comment]
`rebird` v0.5.0 just released on CRAN. @sckott, this should fix all the problems with `spocc`.

**Comment by sckott** [comment]
thanks.

**Comment by sebpardo** [comment]
I just found out the API 1.1 will be shut down on October 1st, so we should get going with making the switch.

**Comment by ateucher** [comment]
@sckott @sebpardo as the new API requires a key (https://ebird.org/api/keygen), should one be included in the package and/or require users to get their own (requires opening an eBird account).

**Comment by sckott** [comment]
if we include an API key in the pkg, i'd ask ebird folks if that's okay first. I kinda lean towards making users get their own - that is, they can't use the pkg unless they have their own key, but what do others think

**Comment by ateucher** [comment]
I agree with you. It's not difficult to get one.

**Comment by ateucher** [comment]
Does rOpenSci have a standard way of dealing with keys? The way I've written now it has to be stored as an env variable, but could also have a `key` argument to every function?

**Comment by sckott** [comment]
there's no official way we deal with keys. I do like to allow env vars (could allow r options too, but i think we should push users to env vars as they're more universal) in addition to allowing passing in as a parameter. BUT also in docs strongly urging users to use env vars so they don't accidentally expose their key. i guess could only allow env var but i worry that makes the first time user experience tough for non-technical folks

**Comment by ateucher** [comment]
>  i worry that makes the first time user experience tough for non-technical folks
Agreed. I also like pushing towards env vars.

**Comment by ateucher** [comment]
Ok, added both options: 7ccd8a775814285102a47e2a01efb28defe3eaac

**Comment by sebpardo** [comment]
+1 to users to getting their own key and store it in env vars.

I'll write a short walk-through on how to obtain and store the key in the README and vignette.

**Comment by sebpardo** [comment]
PR #67 closes this issue.
