### ISSUE TITLE
Wrapper to part of the eBird API

### ISSUE THREAD

**Issue by maelle** [ropensci/rebird#65]
Would it be possible to clarify which webservice(s) from the eBird API are wrapped in this package? I think it'd be an useful addition to the docs.

Once the package has been switched to the new API, asking for contributors to add new endpoints wrappers might be a good way to have first-time contributors?

**Comment by sebpardo** [comment]
That's a good idea! I'll make sure that information is included when we do the switch to the new API in the next few months; I don't think there's any point to do it for the current API given that it will be retired sometime soon so making the switch is priority numero uno.

**Comment by maelle** [comment]
Muy bien! 😉

**Comment by sebpardo** [comment]
I forgot to ask, do you know of any packages that already do this so I can have a better idea of what it should look like?

**Comment by sebpardo** [comment]
Sweet, thank you @maelle !
