### ISSUE TITLE
ebirdregion should return all observations, but fails to return a few, although these may be retrievable by ebirdnotable

### ISSUE THREAD

**Issue by Graskian** [ropensci/rebird#68]
Hello

I love this package. I am wondering how the search is performed though, as there seems to be some inconsistencies..

Consider for instance this checklist from yesterday, Oct 17th: https://ebird.org/view/checklist/S49257480
It contains 72 species. By calling ebirdregion(loc = 'DK') and followingly filtering out that particular location and date, I only get 62 out of 72 observations. 10 are missing, including the notable observation "Dusky Warbler 3".

If I, however use ebirdnotable(loc='DK'), I get two observations that INCLUDES the "Dusky Warbler 3" observation. I suspect there is some delay for recently submitted observations before they are accessible for extraction and this is likely on eBird API's end. In any case though, I would like to hear some feedback from you, whether this is a known issue.

I originally discovered the error simply because ebirdnotable() was able to find this dusky warbler record, while the call ebirdregion(loc = 'DK', species = 'duswar') couldn't. Both functions could however properly extract another Dusky Warbler observation from October 16th, so I will not be surprised if by tomorrow, the ebirdregion() call will be able to retrieve all 72 observations from the checklist in consideration.

So: any explanation for the possible delay and inevitable inconsitency between ebirdnotable and ebirdregion?

Mathias

**Comment by sebpardo** [comment]
Hi Mathias, sorry for the late reply, I was away on holidays. Great to hear you figured this out, and also very happy that you enjoy using rebird!

**Comment by Graskian** [comment]
All good, yes thank you, what a wonderful package!
