### ISSUE TITLE
Would like to contribute a checklist feed function

### ISSUE THREAD

**Issue by mfoos** [ropensci/rebird#78]
Hi folks,

I wrote a function (and tests) to access the checklist feed API endpoint [https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#4416a7cc-623b-4340-ab01-80c599ede73e](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#4416a7cc-623b-4340-ab01-80c599ede73e) 

and then realized that the contributor guidelines say to post before making a PR. Also, I am working with a different version of roxygen, so I'm reluctant to include the man/(filename).Rd file in the commit because the formats are slightly different.

Any thoughts before I make a PR?

thanks!
M

**Comment by sebpardo** [comment]
Hi @mfoos, apologies for the late reply. That would be great and I definitely encourage you to submit a PR with this new function! Ideally the documentation should be in the function file itself (e.g. https://github.com/ropensci/rebird/blob/master/R/ebirdhotspot.R), but I'd be more than happy to contribute to that. We should also build some tests for the function as part of the PR, but we could do that after the function is ready. Thank you for your willingness to contribute!

**Comment by mfoos** [comment]
Yep, the doc is in the function with roxygen comments, I was actually referring to the PR form where it says:

> If you've updated a file in the man-roxygen directory, make sure to update the man/ files by running devtools::document() or similar as .Rd files should be affected by your change
