### ISSUE TITLE
ebirdfreq failure - URL directs to login page(?)

### ISSUE THREAD

**Issue by dbradnum** [ropensci/rebird#82]
Hi,

I'm consistently getting a failure from the ebirdfreq() function. When I try the examples in the package documentation, I get an error as follows:

```r 
> ebirdfreq(loctype = 'hotspots', loc = 'L196159')
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names': ‘    .January-1’, ‘.January-1’, ‘</a>.January-1’, ‘</div>.January-1’, ‘</g>.January-1’, ‘</label>.January-1’, ‘</svg>.January-1’, ‘<g class=LogoLab-ofOrnithology fill=#000 transform=translate(335.03 17.285)>.January-1’, ‘<g class=LogoLab-sapsucker transform=translate(242.966)>.January-1’, ‘<g class=LogoLab-theCornellLab fill=#000 transform=translate(0 17.285)>.January-1’, ‘<path d=M0.138375929,2.72872008 C0.138375929,3.83301149 1.01946082,4.71324377 2.12749183,4.71324377 C3.23285288,4.71324377 4.11393777,3.83301149 4.11660773,2.72872008 C4.11393777,1.6217613 3.23018292,0.741529015 2.12749183,0.738861644 C1.02213078,0.741529015 0.138375929,1.6217613 0.138375929,2.72872008 L0.138375929,2.72872008 Z/>.January-1’, ‘<path d=M134.835358 31.9764382C132.958381 31.9737709 131.81297 30.8268015 131.8103 28.9116295L131.8103 15.0039594 137.881776 15.0039594 137.881776 12.683347 131.8103 12.683347 131.8103 6.57240105 129.212435 6.57240105 129.212435 12.683 [... truncated] 
```
It seems that the call to the URL is returning an HTML document rather than a TSV as expected. I can see that when I try to construct the URL myself - eg https://ebird.org/ebird/barchartData?byr=1900&eyr=2020&bmo=1&emo=12&r=L196159&fmt=tsv - and plug it into Chrome, I get the file I expect.... but I have to be logged in first.

Having now dug into the package source a bit, and stepped through the code up to [here](https://github.com/ropensci/rebird/blob/41e78114d345d5f340021933263f89abc9442b89/R/ebirdfreq.R#L83), it looks like the web response we're getting in R is the eBird log-in page, rather than the lovely TSV data file we want :-( 

I guess maybe something has changed on eBird's end? Worth noting that I do have an ebird access token, and other functions (eg nearestobs(), ebirdregion()) are working fine. But I think this one isn't connected up to the same API, so it's a different case. 

Any suggestions for getting this working again would be much appreciated - and do let me know if you need any more info or I can help otherwise. 

<details> <summary><strong>Session Info</strong></summary>
> devtools::session_info()
- Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United Kingdom.1252 
 ctype    English_United Kingdom.1252 
 tz       Europe/London               
 date     2020-10-22                  

- Packages ----------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)
 backports     1.1.10  2020-09-15 [1] CRAN (R 4.0.3)
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
 cli           2.1.0   2020-10-12 [1] CRAN (R 4.0.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.3)
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.3)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.3)
 devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
 digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.3)
 dplyr         1.0.2   2020-08-18 [1] CRAN (R 4.0.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.3)
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
 generics      0.0.2   2018-11-29 [1] CRAN (R 4.0.3)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)
 htmltools     0.5.0   2020-06-16 [1] CRAN (R 4.0.3)
 httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.3)
 jsonlite      1.7.1   2020-09-07 [1] CRAN (R 4.0.3)
 knitr         1.30    2020-09-22 [1] CRAN (R 4.0.3)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 4.0.3)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.3)
 pillar        1.4.6   2020-07-10 [1] CRAN (R 4.0.3)
 pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.3)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.3)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.3)
 processx      3.4.4   2020-09-03 [1] CRAN (R 4.0.3)
 ps            1.4.0   2020-10-07 [1] CRAN (R 4.0.3)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)
 R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.3)
 rebird      * 1.1.0   2019-10-24 [1] CRAN (R 4.0.3)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.3)
 rlang         0.4.8   2020-10-08 [1] CRAN (R 4.0.3)
 rmarkdown     2.4     2020-09-30 [1] CRAN (R 4.0.3)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.3)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 4.0.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.3)
 tibble        3.0.4   2020-10-12 [1] CRAN (R 4.0.3)
 tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.3)
 usethis       1.6.3   2020-09-17 [1] CRAN (R 4.0.3)
 vctrs         0.3.4   2020-08-29 [1] CRAN (R 4.0.3)
 withr         2.3.0   2020-09-22 [1] CRAN (R 4.0.3)
 xfun          0.18    2020-09-29 [1] CRAN (R 4.0.3)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.3)

[1] C:/Users/dbrad/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library
```r

```
</details>

**Comment by ateucher** [comment]
@dbradnum thanks for the report and I think you've nailed the issue. You previously didn't need to be logged in to get the tsv download, whereas now it appears you do. And you're correct, this function doesn't use the ebird API, rather builds the url to the tsv file (but is then intercepted by the login). 

It's probably worth looking at the API again to see if this functionality can be replicated using an API endpoint.

**Comment by sebpardo** [comment]
Hi @dbradnum, thank you for this. You are indeed correct that something changed on the eBird Central side where now you need to be logged in to do url-based queries. Unfortunately, it doesn't seem we can pass on the API key via url, and the API doesn't have the functionality to do these queries yet, so we can't create an R function, API- or url-based, for this task anymore. 

I think the only realistic solution at this point in time is to remove this function, mark as defunct, and provide a new function that just outputs the url for the user to paste in their browser and obtain a text output file that way.

**Comment by dbradnum** [comment]
Thanks Andy, Seb. I suspected that there might not be much we can do here. 

The only thing I wondered is whether you have contacts at eBird Central, and might be able to ask that this functionality goes onto the list of desirable features for thr API? Clearly they have the ability to generate the stats, so one would hope it's not too big a deal to wrap with the API. But I'm sure they have a bunch of other things to do as well, so I'm not expecting a quick win.

In the meantime, I can't see an alternative to what Seb proposed above.

**Comment by sebpardo** [comment]
I just had a thought. Perhaps we could keep `ebirdfreq()`by using OAuth, see https://github.com/ropensci/rfigshare/blob/master/R/fs_auth.R for an example. This is contingent on eBird using OAuth in the first place, but I imagine they might given they have multiple sites (eBird, Birdsoftheworld, etc.) with the same login. I'll ask eBird Central about this after they complete their db migration next week.

**Comment by ateucher** [comment]
@sebpardo have you managed to connect with eBird Central? I don't think it's set up for OAuth (the website requires username/password). Without it being added to the API I think we're going to have to make this function defunct.

**Comment by VLucet** [comment]
Hi, sorry for the double issue posting, I has missed this conversation. 
Is there any way to produce a similar information than that `ebirdfreq()` is meant to deliver, by doing either of the following:
1. Aggregating the "Historic observations on a date", url is `https://api.ebird.org/v2/data/obs/{{regionCode}}/historic/{{y}}/{{m}}/{{d}}` and seems to accept any location code
2. Using "Recent nearby obsrvations" by first looking up the lat and long of the desired hotspot and placing a request for these coordinates, url format is `https://api.ebird.org/v2/data/obs/geo/recent/{{speciesCode}}?lat={{lat}}&lng={{lng}}`
3. Wait for the in-developpement feature "GET Species List at a Location" (url fornat is `https://api.ebird.org/v2/product/spplist/{{locId}}`)

**Comment by sebpardo** [comment]
@ateucher I emailed them a few days ago but haven't heard back yet.

**Comment by sebpardo** [comment]
Hi @ateucher, I heard back from Tim Lenz and he confirmed that the frequency data isn't available from the API yet, however come January they'll revisit this and might add include it to the API.

This still leaves us with what to do in the meantime. Ideally, when function stops working we need to update the CRAN version to address is as soon as possible. However, making a function defunct only to bring it back again a month or two later seems counterproductive. What do you think? @sckott might have some thoughts as well.

**Comment by sckott** [comment]
Perhaps send a new version to cran, keeping the function, but temporarily have it return an error with a message stating what's going on, maybe linking to this issue

**Comment by ateucher** [comment]
Good to hear @sebpardo, fingers crossed! @sckott I think that's a good idea
