### ISSUE TITLE
Getting nearby hotspots

### ISSUE THREAD

**Issue by VLucet** [ropensci/rebird#83]
Hi, awesome package. Was wondering if there was a way to get a list of hotspots nearby given coordinates. I cannot find an example in the doc. It would basically wrap a querry to[ this address in the api doc](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#674e81c1-6a0c-4836-8a7e-6ea1fe8e6677). 

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by VLucet** [comment]
I just saw that is on the list of requested features... apologies for that. Are you looking for PRs for new features? I could give it a go.

**Comment by sebpardo** [comment]
Hi @VLucet, if you are willing to create a PR to add this functionality that would be most welcome. I'm happy to help with this as well. Note that we have some internal helper functions, such as [`ebird_GET()`](https://github.com/ropensci/rebird/blob/master/R/zzz.R#L31), that make it much more straightforward to do the API requests and create new R functions.
