### ISSUE TITLE
Get species for location / region

### ISSUE THREAD

**Issue by dbradnum** [ropensci/rebird#85]
I recently helped a fellow eBirder answer a question about the total number of species seen at hotspots within a distance of his home. This involved a couple of eBird API functions that aren't yet included in rebird:

1. [Get nearby hotspots](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#674e81c1-6a0c-4836-8a7e-6ea1fe8e6677)
2. [Get species list for a region](https://documenter.getpostman.com/view/664302/S1ENwy59?version=latest#55bd1b26-6951-4a88-943a-d3a8aa1157dd)

I've got R code up and running for both of these now, and am happy to tidy it up and submit as pull requests for the package - hopefully it'll be useful for other people. 
I can see that #83 is already open for the first API call, so I'm raising this to cover the second one.

Hope this all sounds OK? Do let know if there's anything I should bear in mind, or I inadvertantly go astray with the fork > branch > pull request process!

**Comment by sebpardo** [comment]
I just noticed this issue. Turns out I already wrote a function ready that does both the ref/hotspot and ref/hotspot/geo API requests so I'll just upload it now. Would be neat to see how different (or similar) your approach was to mine.
