### ISSUE TITLE
export taxonomy?

### ISSUE THREAD

**Issue by slager** [ropensci/rebird#94]
It could be useful for the package to export the internal taxonomy data object so that other packages can reference that object without getting R CMD CHECK warnings.  Happy to do a PR for this if you're amenable to it.

**Comment by sebpardo** [comment]
Sounds good, please go ahead with a PR.

I'm curious of which warnings you'd get when referencing from other packages, could you please provide an example? Thanks!

**Comment by slager** [comment]
Will send a PR.

Here's the CRAN note:
```
N  checking dependencies in R code (1s)
   Unexported object imported by a ':::' call: ‘rebird:::tax’
     See the note in ?`:::` about the use of this operator.
```
